/**
 * The starting roadmap: features from the ProjectionLab changemap review (Oct 2026), ranked by demand
 * (votes), whether PL has shipped them, our head start, and effort. Seeded once per user; edits live in the DB.
 */

export const ROADMAP_TIERS = ["A", "B", "C"] as const
export type RoadmapTier = (typeof ROADMAP_TIERS)[number]

export const ROADMAP_STATUSES = ["backlog", "next", "building", "done", "skipped"] as const
export type RoadmapStatus = (typeof ROADMAP_STATUSES)[number]

export const ROADMAP_EFFORTS = ["S", "S–M", "M", "M–L", "L"] as const

export interface RoadmapSeed {
  key: string
  tier: RoadmapTier
  rank: number
  title: string
  summary: string
  /** ProjectionLab votes behind it. */
  demand: string
  plStatus: string
  ourStatus: string
  effort: string
  status?: RoadmapStatus
}

export const ROADMAP_SEED: RoadmapSeed[] = [
  {
    key: "live-linked-plans",
    tier: "A",
    rank: 1,
    title: "Live-linked plans",
    summary: "Plan starting balances refresh from linked accounts, drift alerts, and each account's stress-test mix derived from actual holdings.",
    demand: "526 (account linking, PL's #1) · 224 (asset allocation)",
    plStatus: "Linking unbuilt for years; allocation planned",
    ourStatus: "Plans import accounts once; no auto-refresh",
    effort: "M",
  },
  {
    key: "spending-rules",
    tier: "A",
    rank: 2,
    title: "Spending rules in plans",
    summary: "Guardrails, dynamic spending, CAPE-based withdrawals, buckets and flex % inside the plan engine and the stress test.",
    demand: "121 guardrails · 54 dynamic · 42 CAPE · 29+15 buckets · 122 flex (shipped)",
    plStatus: "Flex shipped; the rest unbuilt",
    ourStatus: "Strategies exist in the FIRE lab only (withdrawal-strategies.ts)",
    effort: "M",
  },
  {
    key: "failure-solvers",
    tier: "A",
    rank: 3,
    title: "Failure insights & solvers",
    summary: "Why a plan fails, the max safe spending, and the earliest retirement at X% success, solved against the stress engine.",
    demand: "34 insights + 52 decision variables (planned) · 11 max spending · 12 retire at X%",
    plStatus: "Planned",
    ourStatus: "Stress engine ready to solve against",
    effort: "M",
  },
  {
    key: "plan-branching",
    tier: "A",
    rank: 4,
    title: "Plan branching",
    summary: "Variants inherit from a base plan, edits can apply to all plans, and a diff shows which inputs changed.",
    demand: "267 (PL's #1 planned) · 147 clones follow base · 30 + 24 diffs · 24 edit across plans",
    plStatus: "Planned",
    ourStatus: "Separate plans plus a Compare page",
    effort: "M–L",
  },
  {
    key: "equity-comp",
    tier: "A",
    rank: 5,
    title: "Equity compensation",
    summary: "RSU vesting schedules, ESPP and stock options as income and holdings in the plan.",
    demand: "225 RSU vesting · 27+10 ESPP · 61 stock options",
    plStatus: "RSU unbuilt; options planned",
    ourStatus: "None",
    effort: "M",
  },
  {
    key: "ai-copilot",
    tier: "A",
    rank: 6,
    title: "AI copilot / MCP over plans",
    summary: "PocketLLM and the MCP server can read plans, stress results, the ledger and live accounts, and answer what-ifs.",
    demand: "74 MCP · 22 ChatGPT · AI assistant / guidance asks",
    plStatus: "Closed as duplicates",
    ourStatus: "PocketLLM + MCP server exist; they don't see plans",
    effort: "M",
  },
  {
    key: "expense-itemizer",
    tier: "A",
    rank: 7,
    title: "Expense itemizer with templates",
    summary: "Itemized living expenses with templates, seeded from real spending and budgets.",
    demand: "124 itemizer (planned) · 26 roll-up of expenses",
    plStatus: "Planned",
    ourStatus: "Import from budgets / averages / medians exists; templates missing",
    effort: "S",
  },
  {
    key: "monte-carlo",
    tier: "B",
    rank: 8,
    title: "Monte Carlo alongside history",
    summary: "Monte Carlo / bootstrap runs next to the historical replay: histogram, filter trials, compare across plans.",
    demand: "Shipped by PL long ago · 29 compare across plans · 20 per-account trials · 8 filter trials",
    plStatus: "Shipped",
    ourStatus: "Shipped: Stress test simulated markets (block bootstrap, random restart, random years) + history replay; histogram filter, trial table, Compare row",
    effort: "M",
  },
  {
    key: "exports",
    tier: "B",
    rank: 9,
    title: "PDF report & CSV export",
    summary: "A shareable PDF plan report and CSV of the ledger and cash flow.",
    demand: "149 PDF reports (shipped) · 100 tabular cash flow · 9 export",
    plStatus: "Shipped",
    ourStatus: "Ledger table only",
    effort: "M",
  },
  {
    key: "conditional-milestones",
    tier: "B",
    rank: 10,
    title: "Milestones on conditions",
    summary: "Milestones that trigger when invested money reaches $X, the FI number is hit, or other plan conditions.",
    demand: "Shipped early by PL · 34 more milestone types · 15 complex criteria",
    plStatus: "Shipped",
    ourStatus: "Age / year / milestone timing only",
    effort: "M",
  },
  {
    key: "roth-conversions",
    tier: "B",
    rank: 11,
    title: "Roth conversions & drawdown to a bracket",
    summary: "Roth conversions by bracket or amount and drawdown up to a tax bracket, with an optimizer.",
    demand: "238 · 92 · 70 · 333 Optimizers (all shipped Apr 2026)",
    plStatus: "Shipped",
    ourStatus: "Tax brackets exist; no conversions",
    effort: "L",
  },
  {
    key: "social-security",
    tier: "B",
    rank: 12,
    title: "Social Security estimator",
    summary: "Estimate benefits from earnings and claiming age; feed them into the plan as income.",
    demand: "134 (shipped)",
    plStatus: "Shipped",
    ourStatus: "None",
    effort: "M",
  },
  {
    key: "scheduled-transfers",
    tier: "B",
    rank: 13,
    title: "Scheduled transfers between accounts",
    summary: "One-time or recurring transfers between plan accounts.",
    demand: "124 (shipped)",
    plStatus: "Shipped",
    ourStatus: "Kids' 529 transfers only",
    effort: "S–M",
  },
  {
    key: "plan-history",
    tier: "B",
    rank: 14,
    title: "Undo & version history",
    summary: "Undo recent edits and browse earlier versions of a plan.",
    demand: "74 (planned) · 8 undo button",
    plStatus: "Planned",
    ourStatus: "None",
    effort: "S–M",
  },
  {
    key: "loan-depth",
    tier: "B",
    rank: 15,
    title: "Loan depth",
    summary: "Refinance, HELOC, variable-rate, interest-only and multiple mortgages.",
    demand: "56 HELOC · 24 variable rate · 10 interest-only · 9 refinance · 5 multiple mortgages",
    plStatus: "Variable rate planned; rest unbuilt",
    ourStatus: "Fixed-rate loans with principal / interest split",
    effort: "M",
  },
  {
    key: "small-tax-items",
    tier: "B",
    rank: 16,
    title: "Mortgage-interest deduction & loss carryforward",
    summary: "Itemize mortgage interest in bracket tax mode; carry capital losses forward (matters for trading).",
    demand: "47 mortgage interest · 30 capital loss carryforward",
    plStatus: "Unbuilt",
    ourStatus: "Per-loan interest split ready to use",
    effort: "S",
  },
  {
    key: "i-bonds",
    tier: "B",
    rank: 17,
    title: "I Bonds account type",
    summary: "Series I bonds with their rate, purchase limits and holding rules.",
    demand: "93",
    plStatus: "Unbuilt",
    ourStatus: "None",
    effort: "S",
  },
  {
    key: "monthly-sim",
    tier: "C",
    rank: 18,
    title: "Monthly simulation",
    summary: "Monthly instead of yearly steps.",
    demand: "163",
    plStatus: "Unbuilt",
    ourStatus: "Yearly engine; would mean a rewrite",
    effort: "L",
    status: "skipped",
  },
  {
    key: "family-accounts",
    tier: "C",
    rank: 19,
    title: "Family accounts",
    summary: "Several people sharing one household plan and login.",
    demand: "245",
    plStatus: "Unbuilt",
    ourStatus: "Single-user; a multi-user product decision",
    effort: "L",
  },
  {
    key: "multi-currency",
    tier: "C",
    rank: 20,
    title: "Multi-currency & international tax",
    summary: "Plans in other currencies and countries' tax systems.",
    demand: "148 multi-currency · many country presets",
    plStatus: "Planned / PL's moat",
    ourStatus: "US only",
    effort: "L",
    status: "skipped",
  },
  {
    key: "rental-series",
    tier: "C",
    rank: 21,
    title: "Rental & mortgage event series",
    summary: "Rentals and owner-occupancy as a series of events; mortgage series per home.",
    demand: "94 rental · 91 mortgage series",
    plStatus: "Planned",
    ourStatus: "Homes, financing and running costs; no rental income",
    effort: "M–L",
  },
  {
    key: "annuities-estate",
    tier: "C",
    rank: 22,
    title: "Annuities & legacy planning",
    summary: "Buying an annuity; estate and legacy views.",
    demand: "36 annuity · 45 legacy",
    plStatus: "Unbuilt",
    ourStatus: "Inheritance received only",
    effort: "M",
  },
]
